Update patch set 2
Patch Set 2:

Not at all sure if a change in the golang version caused this failure, or something else:

    18:41:45 --- FAIL: TestSubReqAndSubDelOkSameAction (15.02s)

Does this look familiar?

Patch-set: 2
Reviewer: Gerrit User 1000036 <1000036@84e4e190-e623-4c37-9eda-58b1937c1b53>
Reviewer: Gerrit User 1000014 <1000014@84e4e190-e623-4c37-9eda-58b1937c1b53>